apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-app
spec:
  replicas: 1  
  selector:
    matchLabels:
      app: consumer-app
  template:
    metadata:
      labels:
        app: consumer-app
    spec:
      containers:
      - name: consumer-app
        image: your-consumer-image:latest  
        ports:
        - containerPort: 8080
