apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer-app
spec:
  replicas: 1  
  selector:
    matchLabels:
      app: producer-app
  template:
    metadata:
      labels:
        app: producer-app
    spec:
      containers:
      - name: producer-app
        image: your-producer-image:latest  
        ports:
        - containerPort: 8080
