apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zookeeper
spec:
  replicas: 3  
  selector:
    matchLabels:
      app: zookeeper
  serviceName: zookeeper  
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
      - name: zookeeper
        image: confluentinc/cp-zookeeper:latest  
        ports:
        - containerPort: 2181
        env:
        - name: ZOOKEEPER_CLIENT_PORT
          value: "2181"

---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
spec:
  clusterIP: None  
  ports:
  - port: 2181
    targetPort: 2181
  selector:
    app: zookeeper
